from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

import os


def export_pdf(
    content: str,
    filename: str
):

    os.makedirs(
        "exports",
        exist_ok=True
    )

    path = f"exports/{filename}"

    doc = SimpleDocTemplate(path)

    styles = getSampleStyleSheet()

    elements = []

    title = filename.replace(
        ".pdf",
        ""
    ).replace(
        "_",
        " "
    ).title()

    elements.append(
        Paragraph(
            title,
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    for line in content.split("\n"):

        if line.strip():

            elements.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

            # elements.append(
            #     Spacer(1, 6)
            # )

            # elements.append(
            #     Spacer(1, 20)
            # )
    
    elements.append(
        Paragraph(
            "Generated by StudyMate",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return path