from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.units import mm

import os

def add_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont(
        "Helvetica-Oblique",
        8
    )

    canvas.drawRightString(
        200 * mm,
        10 * mm,
        "Generated by StudyMate"
    )

    canvas.restoreState()

def export_pdf(
    content: str,
    filename: str
):

    os.makedirs(
        "exports",
        exist_ok=True
    )

    path = f"exports/{filename}"

    doc = SimpleDocTemplate(path)

    styles = getSampleStyleSheet()

    elements = []

    title = filename.replace(
        ".pdf",
        ""
    ).replace(
        "_",
        " "
    ).title()

    elements.append(
        Paragraph(
            title,
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    for line in content.split("\n"):

        if line.strip():

            elements.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

            # elements.append(
            #     Spacer(1, 6)
            # )

            # elements.append(
            #     Spacer(1, 20)
            # )

    doc.build(
        elements,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )

    return path